name: Java CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11, 17]

  steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distributions: temurin
        java-version: ${{matrix.java-version}}

    - name: Build with maven
      run: mvn -B package --file pom.xml

    - name: Test Run
      run: mvn test
